// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

public class Atividade extends MModel {
	private String code;
	private String text;

	@java.lang.SuppressWarnings("all")
	public String getCode() {
		return this.code;
	}

	@java.lang.SuppressWarnings("all")
	public String getText() {
		return this.text;
	}

	@java.lang.SuppressWarnings("all")
	public void setCode(final String code) {
		this.code = code;
	}

	@java.lang.SuppressWarnings("all")
	public void setText(final String text) {
		this.text = text;
	}
}
