// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

public class MInscricaoEstadual {
	private String uf;
	private String ie;
	private String sie;

	@java.lang.SuppressWarnings("all")
	public String getUf() {
		return this.uf;
	}

	@java.lang.SuppressWarnings("all")
	public String getIe() {
		return this.ie;
	}

	@java.lang.SuppressWarnings("all")
	public String getSie() {
		return this.sie;
	}

	@java.lang.SuppressWarnings("all")
	public void setUf(final String uf) {
		this.uf = uf;
	}

	@java.lang.SuppressWarnings("all")
	public void setIe(final String ie) {
		this.ie = ie;
	}

	@java.lang.SuppressWarnings("all")
	public void setSie(final String sie) {
		this.sie = sie;
	}
}
