// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public class PessoaJuridica extends Pessoa {
	private String cnpj;
	private String fantasia;
	private String abertura;
	private String situacao;
	private String naturezaJuridica;
	private String tipo;
	private String logradouro;
	private String numero;
	private String cep;
	private String bairro;
	private String municipio;
	private String uf;
	private Vinculo vinculo;
//	logradouro numero bairro municipio uf
	private BigDecimal capitalSocial;
	private String scapitalSocial;
	private String satividadePrincipal;
	private List<Atividade> atividadePrincipal;
	private List<Atividade> atividadesSecundarias;
	private List<Socio> qsa;
	private Map<String, QualGrupo> mapSocios;

	@java.lang.SuppressWarnings("all")
	public void setCnpj(final String cnpj) {
		this.cnpj = cnpj;
	}

	@java.lang.SuppressWarnings("all")
	public void setFantasia(final String fantasia) {
		this.fantasia = fantasia;
	}

	@java.lang.SuppressWarnings("all")
	public void setAbertura(final String abertura) {
		this.abertura = abertura;
	}

	@java.lang.SuppressWarnings("all")
	public void setSituacao(final String situacao) {
		this.situacao = situacao;
	}

	@java.lang.SuppressWarnings("all")
	public void setNaturezaJuridica(final String naturezaJuridica) {
		this.naturezaJuridica = naturezaJuridica;
	}

	@java.lang.SuppressWarnings("all")
	public void setTipo(final String tipo) {
		this.tipo = tipo;
	}

	@java.lang.SuppressWarnings("all")
	public void setLogradouro(final String logradouro) {
		this.logradouro = logradouro;
	}

	@java.lang.SuppressWarnings("all")
	public void setNumero(final String numero) {
		this.numero = numero;
	}

	@java.lang.SuppressWarnings("all")
	public void setCep(final String cep) {
		this.cep = cep;
	}

	@java.lang.SuppressWarnings("all")
	public void setBairro(final String bairro) {
		this.bairro = bairro;
	}

	@java.lang.SuppressWarnings("all")
	public void setMunicipio(final String municipio) {
		this.municipio = municipio;
	}

	@java.lang.SuppressWarnings("all")
	public void setUf(final String uf) {
		this.uf = uf;
	}

	@java.lang.SuppressWarnings("all")
	public void setVinculo(final Vinculo vinculo) {
		this.vinculo = vinculo;
	}

	@java.lang.SuppressWarnings("all")
	public void setCapitalSocial(final BigDecimal capitalSocial) {
		this.capitalSocial = capitalSocial;
	}

	@java.lang.SuppressWarnings("all")
	public void setScapitalSocial(final String scapitalSocial) {
		this.scapitalSocial = scapitalSocial;
	}

	@java.lang.SuppressWarnings("all")
	public void setSatividadePrincipal(final String satividadePrincipal) {
		this.satividadePrincipal = satividadePrincipal;
	}

	@java.lang.SuppressWarnings("all")
	public void setAtividadePrincipal(final List<Atividade> atividadePrincipal) {
		this.atividadePrincipal = atividadePrincipal;
	}

	@java.lang.SuppressWarnings("all")
	public void setAtividadesSecundarias(final List<Atividade> atividadesSecundarias) {
		this.atividadesSecundarias = atividadesSecundarias;
	}

	@java.lang.SuppressWarnings("all")
	public void setQsa(final List<Socio> qsa) {
		this.qsa = qsa;
	}

	@java.lang.SuppressWarnings("all")
	public void setMapSocios(final Map<String, QualGrupo> mapSocios) {
		this.mapSocios = mapSocios;
	}

	@java.lang.SuppressWarnings("all")
	public String getCnpj() {
		return this.cnpj;
	}

	@java.lang.SuppressWarnings("all")
	public String getFantasia() {
		return this.fantasia;
	}

	@java.lang.SuppressWarnings("all")
	public String getAbertura() {
		return this.abertura;
	}

	@java.lang.SuppressWarnings("all")
	public String getSituacao() {
		return this.situacao;
	}

	@java.lang.SuppressWarnings("all")
	public String getNaturezaJuridica() {
		return this.naturezaJuridica;
	}

	@java.lang.SuppressWarnings("all")
	public String getTipo() {
		return this.tipo;
	}

	@java.lang.SuppressWarnings("all")
	public String getLogradouro() {
		return this.logradouro;
	}

	@java.lang.SuppressWarnings("all")
	public String getNumero() {
		return this.numero;
	}

	@java.lang.SuppressWarnings("all")
	public String getCep() {
		return this.cep;
	}

	@java.lang.SuppressWarnings("all")
	public String getBairro() {
		return this.bairro;
	}

	@java.lang.SuppressWarnings("all")
	public String getMunicipio() {
		return this.municipio;
	}

	@java.lang.SuppressWarnings("all")
	public String getUf() {
		return this.uf;
	}

	@java.lang.SuppressWarnings("all")
	public Vinculo getVinculo() {
		return this.vinculo;
	}

	@java.lang.SuppressWarnings("all")
	public BigDecimal getCapitalSocial() {
		return this.capitalSocial;
	}

	@java.lang.SuppressWarnings("all")
	public String getScapitalSocial() {
		return this.scapitalSocial;
	}

	@java.lang.SuppressWarnings("all")
	public String getSatividadePrincipal() {
		return this.satividadePrincipal;
	}

	@java.lang.SuppressWarnings("all")
	public List<Atividade> getAtividadePrincipal() {
		return this.atividadePrincipal;
	}

	@java.lang.SuppressWarnings("all")
	public List<Atividade> getAtividadesSecundarias() {
		return this.atividadesSecundarias;
	}

	@java.lang.SuppressWarnings("all")
	public List<Socio> getQsa() {
		return this.qsa;
	}

	@java.lang.SuppressWarnings("all")
	public Map<String, QualGrupo> getMapSocios() {
		return this.mapSocios;
	}
}
