// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

import java.io.Serializable;
import java.util.Date;

public class PessoaFisica extends MModel implements Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String cpf;
	private String nome;
	private Date nascimento;
	private Integer sexo;
	private Integer estadoCivil;

	@java.lang.SuppressWarnings("all")
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getCpf() {
		return this.cpf;
	}

	@java.lang.SuppressWarnings("all")
	public String getNome() {
		return this.nome;
	}

	@java.lang.SuppressWarnings("all")
	public Date getNascimento() {
		return this.nascimento;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getSexo() {
		return this.sexo;
	}

	@java.lang.SuppressWarnings("all")
	public Integer getEstadoCivil() {
		return this.estadoCivil;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setCpf(final String cpf) {
		this.cpf = cpf;
	}

	@java.lang.SuppressWarnings("all")
	public void setNome(final String nome) {
		this.nome = nome;
	}

	@java.lang.SuppressWarnings("all")
	public void setNascimento(final Date nascimento) {
		this.nascimento = nascimento;
	}

	@java.lang.SuppressWarnings("all")
	public void setSexo(final Integer sexo) {
		this.sexo = sexo;
	}

	@java.lang.SuppressWarnings("all")
	public void setEstadoCivil(final Integer estadoCivil) {
		this.estadoCivil = estadoCivil;
	}
}
