// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

public class Pessoa extends MModel {
	public static final int FISICA = 0;
	public static final int JURIDICA = 1;
	public static final int NONE = 2;
	public static final int SEXO_MASCULINO = 1;
	public static final int SEXO_FEMININO = 0;
	public static final int ESTADO_CIVIL_SOLTEIRO = 0;
	public static final int ESTADO_CIVIL_CASADO = 1;
	public static final int ESTADO_CIVIL_DIVORCIADO = 2;
	public static final int ESTADO_CIVIL_SEPARADO_JUDICIAL = 3;
	public static final int ESTADO_CIVIL_VIUVO = 4;
	public static final int ESTADO_CIVIL_UNIAO_ESTAVEL = 5;
	private Long id;
	private String nome;
	private boolean noContainCpfCnpj;

	@java.lang.SuppressWarnings("all")
	public Long getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getNome() {
		return this.nome;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isNoContainCpfCnpj() {
		return this.noContainCpfCnpj;
	}

	@java.lang.SuppressWarnings("all")
	public void setId(final Long id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setNome(final String nome) {
		this.nome = nome;
	}

	@java.lang.SuppressWarnings("all")
	public void setNoContainCpfCnpj(final boolean noContainCpfCnpj) {
		this.noContainCpfCnpj = noContainCpfCnpj;
	}
}
