// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

import java.util.List;

public class QualGrupo extends MModel {
	private String codigo;
	private String descricao;
	private List<Socio> socios;

	@java.lang.SuppressWarnings("all")
	public String getCodigo() {
		return this.codigo;
	}

	@java.lang.SuppressWarnings("all")
	public String getDescricao() {
		return this.descricao;
	}

	@java.lang.SuppressWarnings("all")
	public List<Socio> getSocios() {
		return this.socios;
	}

	@java.lang.SuppressWarnings("all")
	public void setCodigo(final String codigo) {
		this.codigo = codigo;
	}

	@java.lang.SuppressWarnings("all")
	public void setDescricao(final String descricao) {
		this.descricao = descricao;
	}

	@java.lang.SuppressWarnings("all")
	public void setSocios(final List<Socio> socios) {
		this.socios = socios;
	}
}
