// Generated by delombok at Sun Jun 14 17:50:45 BRT 2020
package com.m4rc310.ml.models;

public class Socio extends MModel {
	private String qual;
	private String nome;

	@java.lang.SuppressWarnings("all")
	public String getQual() {
		return this.qual;
	}

	@java.lang.SuppressWarnings("all")
	public String getNome() {
		return this.nome;
	}

	@java.lang.SuppressWarnings("all")
	public void setQual(final String qual) {
		this.qual = qual;
	}

	@java.lang.SuppressWarnings("all")
	public void setNome(final String nome) {
		this.nome = nome;
	}
}
